{application,phoenix_ecto,
             [{description,"Integration between Phoenix & Ecto"},
              {modules,['Elixir.Phoenix.Ecto',
                        'Elixir.Phoenix.Ecto.SQL.Sandbox',
                        'Elixir.Phoenix.HTML.FormData.Ecto.Changeset',
                        'Elixir.Phoenix.HTML.Safe.Decimal',
                        'Elixir.Phoenix.HTML.Safe.Ecto.Date',
                        'Elixir.Phoenix.HTML.Safe.Ecto.DateTime',
                        'Elixir.Phoenix.HTML.Safe.Ecto.Time',
                        'Elixir.Plug.Exception.Ecto.CastError',
                        'Elixir.Plug.Exception.Ecto.NoResultsError',
                        'Elixir.Plug.Exception.Ecto.Query.CastError']},
              {registered,[]},
              {vsn,"3.2.1"},
              {applications,[kernel,stdlib,elixir,logger,ecto,plug]}]}.
