{application,ecto_autoslug_field,
             [{description,"Autoslug field for Ecto."},
              {modules,['Elixir.EctoAutoslugField',
                        'Elixir.EctoAutoslugField.Slug',
                        'Elixir.EctoAutoslugField.SlugBase',
                        'Elixir.EctoAutoslugField.SlugGenerator',
                        'Elixir.EctoAutoslugField.Type']},
              {registered,[]},
              {vsn,"0.2.1"},
              {applications,[kernel,stdlib,elixir,logger]}]}.
