use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# FirestormWeb.Web.Endpoint.load_from_system_env/1 dynamically.
# Any dynamic configuration should be moved to such function.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :firestorm_web, FirestormWeb.Web.Endpoint,
  on_init: {FirestormWeb.Web.Endpoint, :load_from_system_env, []},
  url: [scheme: "https", host: "forum.firestormforum.org", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  instrumenters: [PryIn.Instrumenter, Appsignal.Phoenix.Instrumenter]

# Should we send instrumentation to PryIn?
# NOTE: We should really just use the existing pryin config instead of adding
# this, but I'll deal with it later.
config :firestorm_web, use_pryin: true

config :phoenix, :template_engines,
  eex: Appsignal.Phoenix.Template.EExEngine,
  exs: Appsignal.Phoenix.Template.ExsEngine

# Do not print debug messages in production
config :logger, level: :info

config :firestorm_web, FirestormWeb.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: true,
  loggers: [Appsignal.Ecto, Ecto.LogEntry]

config :pryin,
  enabled: true,
  env: :prod

config :appsignal, :config,
  name: System.get_env("APPSIGNAL_APP_NAME"),
  env: System.get_env("APPSIGNAL_APP_ENV"),
  push_api_key: System.get_env("APPSIGNAL_PUSH_API_KEY"),
  active: true

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :firestorm_web, FirestormWeb.Web.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :firestorm_web, FirestormWeb.Web.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :firestorm_web, FirestormWeb.Web.Endpoint, server: true
