{application,oauth2,
             [{description,"An Elixir OAuth 2.0 Client Library"},
              {modules,['Elixir.OAuth2','Elixir.OAuth2.AccessToken',
                        'Elixir.OAuth2.Client','Elixir.OAuth2.Error',
                        'Elixir.OAuth2.Request','Elixir.OAuth2.Response',
                        'Elixir.OAuth2.Serializer',
                        'Elixir.OAuth2.Serializer.NullSerializer',
                        'Elixir.OAuth2.Strategy',
                        'Elixir.OAuth2.Strategy.AuthCode',
                        'Elixir.OAuth2.Strategy.ClientCredentials',
                        'Elixir.OAuth2.Strategy.Password',
                        'Elixir.OAuth2.Strategy.Refresh',
                        'Elixir.OAuth2.Util']},
              {registered,[]},
              {vsn,"0.9.0"},
              {applications,[kernel,stdlib,elixir,logger,hackney]},
              {env,[{serializers,#{<<"application/json">> => 'Elixir.Poison'}}]}]}.
